services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/realworld?sslmode=disable

  db:
    image: postgres:17.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realworld
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "5433:5432"

  migrations:
    image: amacneil/dbmate:latest
    volumes:
      - ./db/migrations:/db/migrations
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/realworld?sslmode=disable
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy

  test:
    image: usebruno/cli:latest-debian
    volumes:
      - ./tests:/tests
    # entrypoint: sh -c "/tests/run-api-tests-bruno.sh" 
    entrypoint: sh -c "/tests/run-api-tests-bruno.sh" 
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      api:
        condition: service_started
