services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/conduit?sslmode=disable
      - JWT_SECRET=LSatqj0GuxXGgtRX7LiKu9GM4uyVfUqjS9keNuL574Y
      - PORT=3000
    command: ["./build/conduit", "-log", "-b", "0.0.0.0"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost:3000/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  db:
    image: postgres:17.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conduit
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "5433:5432"

  migrations:
    image: amacneil/dbmate:latest
    volumes:
      - ./db/migrations:/db/migrations
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/conduit?sslmode=disable
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
  test-api:
    image: usebruno/cli:latest
    working_dir: /bruno
    volumes:
      - ./tests/bruno:/bruno
    command: run -r --env-var host=http://api:3000
    depends_on:
      api:
        condition: service_healthy

  test-unit:
    build: .
    command: ["make", "test"]