services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/conduit?sslmode=disable
      - JWT_SECRET=LSatqj0GuxXGgtRX7LiKu9GM4uyVfUqjS9keNuL574Y

  db:
    image: postgres:17.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conduit
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "5433:5432"

  migrations:
    image: amacneil/dbmate:latest
    volumes:
      - ./db/migrations:/db/migrations
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/conduit?sslmode=disable
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
